  version: "3.9"

  services:
    fastapi:
      build: .
      container_name: fastapi-app
      ports:
        - "8001:8000"
      volumes:
        - ../files/uploads:/app/uploads   # persistent uploaded files
        - ./files/ravinkazo.db:/app/ravinkazo.db  # persistent SQLite DB
      restart: always
