"""Add email to Experience model

Revision ID: 1a44f8047be2
Revises: 9f48a27f8cfb
Create Date: 2025-11-15 07:14:30.858488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.db.database import Base
from app.models import *


# revision identifiers, used by Alembic.
revision: str = '1a44f8047be2'
down_revision: Union[str, Sequence[str], None] = '9f48a27f8cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema based on the model definitions."""
    # ### commands auto-generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiences', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema based on the model definitions."""
    # ### commands auto-generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiences', 'email')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
