"""Remove test model

Revision ID: 9f48a27f8cfb
Revises: 139fd9116b3f
Create Date: 2025-11-15 03:31:05.343583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.db.database import Base
from app.models import *


# revision identifiers, used by Alembic.
revision: str = '9f48a27f8cfb'
down_revision: Union[str, Sequence[str], None] = '139fd9116b3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema based on the model definitions."""
    # ### commands auto-generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tests_id'), table_name='tests')
    op.drop_index(op.f('ix_tests_name'), table_name='tests')
    op.drop_table('tests')
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema based on the model definitions."""
    # ### commands auto-generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tests_name'), 'tests', ['name'], unique=False)
    op.create_index(op.f('ix_tests_id'), 'tests', ['id'], unique=False)
    # ### end Alembic commands ###
    # ### end Alembic commands ###
